{% set name = "ansible" %}
{% set version = "9.1.0" %}

{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ad94991fb0e0e53a770a9ffcf1b68047f61b2282d948a7d2682ecd8fb8fa1bf

build:
  number: 0
  entry_points:
    - ansible-community=ansible_collections.ansible_community:main
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - ansible-core >=2.16.1,<2.17.0a0
    # https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows
    - __unix

    # Only require dependencies for a core set of modules (mostly filters from
    # the `ansible.utils` and `community.general` collections).  Dependencies
    # needed for modules in other collections to properly function will be
    # handled by separate `ansible-*` meta-packages.
    - jinja2
    - jmespath
    - netaddr
    - pyyaml

test:
  commands:
    - ansible-community --version
  imports:
    - ansible_collections

about:
  home: https://ansible.com/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Ansible is a radically simple IT automation platform
  description: >
    Ansible is a radically simple IT automation system. It makes applications
    and systems easier to deploy by handling configuration management,
    application deployment, cloud provisioning, ad-hoc task execution, network
    automation, and multi-node orchestration.

    This package includes all collections from the (upstream) Ansible community
    package.  It also installs dependencies for a core set of modules, mostly
    filters from the `ansible.utils` and `community.general` collections.
  doc_url: https://docs.ansible.com/ansible/latest/index.html
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - brainstorm
    - tschoonj
    - pavelzw
    - chenghlee
