{% set name = "ansible" %}
{% set version = "6.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5fa9fc15a8d45c8d5247a9645b0b48f995d735b12c4da655666d48506273526

build:
  number: 0
  skip: true  # [win or py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - ansible-core >=2.13.3,<2.14.0a0

    # Only require dependencies for a core set of modules (mostly filters from
    # the `ansible.utils` and `community.general` collections).  Dependencies
    # needed for modules in other collections to properly function will be
    # handled by separate `ansible-*` meta-packages.
    - jinja2
    - jmespath
    - netaddr
    - pyyaml

test:
  commands:
    - ansible-community --version
  imports:
    - ansible
    - ansible.constants
    - ansible.errors
    - ansible.utils

about:
  home: https://ansible.com/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Ansible is a radically simple IT automation platform
  description: >
    Ansible is a radically simple IT automation system. It makes applications
    and systems easier to deploy by handling configuration management,
    application deployment, cloud provisioning, ad-hoc task execution, network
    automation, and multi-node orchestration.

    This package includes all collections from the (upstream) Ansible community
    package.  It also installs dependencies for a core set of modules, mostly
    filters from the `ansible.utils` and `community.general` collections.
  doc_url: https://docs.ansible.com/ansible/latest/index.html
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - brainstorm
    - tschoonj
    - chenghlee
